# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: gDRutils

on:
  push:
  schedule:
    - cron: '0 3 * * 1-5'

jobs:
  build_and_test:
    runs-on: ubuntu-18.04
    env:
      GITHUB_TOKEN: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
      TEST_TAG: user/app:latest-${{ github.sha }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
          build-args:
            GITHUB_TOKEN=${{ secrets.PRIVATE_ACCESS_TOKEN }}

      - name: Run tests
        run: |
          docker run -v `pwd`:/mnt/vol ${{ env.TEST_TAG }} bash -c 'bash /mnt/vol/rplatform/run_tests.sh /mnt/vol/gDRutils'
